name: Build and Release Flutter App (Unsigned)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build unsigned APK
        run: flutter build apk --release

      - name: Build unsigned AAB
        run: flutter build appbundle --release

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Package .ipa manually
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r unsigned.ipa Payload
        working-directory: .

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: unsigned.ipa

  release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android
          path: artifacts/android

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios
          path: artifacts/ios

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/android/*.apk
            artifacts/android/*.aab
            artifacts/ios/unsigned.ipa
